name: 'Hello World'
description: 'Greet someone'
inputs:
  filename: 
    description: 'The File Name'
    required: true
runs:
  using: "composite"
  steps:
    - run: cat ${{ inputs.filename }}
      shell: bash
